apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: achivement2-deployment
  name: achivement2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: achivement2-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: achivement2-deployment
    spec:
      containers:
      - image: dockerpython
        name: dockerpython
        env:
          - name: POSTGRES_DB
            value: "storage"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "test123"
          - name: PORT_DB
            value: "5432"



