apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: achivement2-deployment
  name: achivement2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: achivement2-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: achivement2-deployment
    spec:
      containers:
      - image: insincere/ach2
        name: dockerpython
        ports: 
        - containerPort: 5000
        env:
          - name: POSTGRES_DB
            value: "storage"
          - name: POSTGRES_USER
            value: "guest"
          - name: POSTGRES_PASSWORD
            value: "12345678"
          - name: PORT_DB
            value: "5432"
          - name: SQLALCHEMY_DATABASE_URI
            value: "postgresql://guest:12345678@91.77.169.186:5432/storage"
