apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: achivement2-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/rewrites: >
      serviceName=achivement2-service rewrite=/;
spec:
  rules:
  - host: node-10.fergus.host
  - http:
      paths:
      - pathType: Prefix
        path: /newValue
        backend:
          service:
            name: achivement2-service
            port:
              number: 80
