apiVersion: v1
kind: Service
metadata:
  name: achivement2-deployment
spec:
  selector:
    app: achivement2-deployment
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000

