apiVersion: v1
kind: Service
metadata:
  labels:
    run: achivement2-deployment
  name: achivement2-deployment
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: achivement2-deployment
  type: NodePort